<?php

declare(strict_types=1);

/**
 * This file is part of the TWB5Widgets package
 *
 * https://github.com/VitexSoftware/php-ease-twbootstrap5-widgets
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\TWB5\Widgets;

use Ease\TWB5\Widgets\MainPageMenu;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-04-16 at 11:53:29.
 */
class MainPageMenuTest extends \PHPUnit\Framework\TestCase
{
    protected MainPageMenu $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new MainPageMenu();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        $this->object = null;
    }

    /**
     * @covers \Ease\TWB5\Widgets\MainPageMenu::addMenuItem
     */
    public function testAddMenuItem(): void
    {
        $title = 'Test Title';
        $url = 'https://example.com';
        $image = 'https://example.com/image.jpg';
        $description = 'Test Description';
        $buttonText = 'Click Me';
        $properties = ['class' => 'custom-card'];

        $result = $this->object->addMenuItem($title, $url, $image, $description, $buttonText, $properties);

        $this->assertInstanceOf(\Ease\TWB5\Row::class, $result);
        $this->assertStringContainsString($title, (string) $result);
        $this->assertStringContainsString($url, (string) $result);
        $this->assertStringContainsString($image, (string) $result);
        $this->assertStringContainsString($description, (string) $result);
        $this->assertStringContainsString($buttonText, (string) $result);
    }

    /**
     * @covers \Ease\TWB5\Widgets\MainPageMenu::__construct
     */
    public function testConstructor(): void
    {
        $this->assertInstanceOf(MainPageMenu::class, $this->object);
        $this->assertEquals('container', $this->object->getTagProperty('class'));
        $this->assertEquals('margin: auto;', $this->object->getTagProperty('style'));
    }
}
