<?php

namespace Test\Ease\TWB5\Widgets;

use Ease\TWB5\Widgets\Selectized;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-04-16 at 11:53:29.
 */
class SelectizedTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Selectized
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Selectized();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Ease\TWB5\Widgets\Selectized::finalize
     * @todo   Implement testfinalize().
     */
    public function testfinalize() {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\TWB5\Widgets\Selectized::selectize
     * @todo   Implement testselectize().
     */
    public function testselectize() {
        $this->assertEquals('', $this->object->selectize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
