<?php

namespace Test\Ease\TWB5\Widgets;

use Ease\TWB5\Widgets\Toggle;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-04-16 at 11:53:29.
 */
class ToggleTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Toggle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Toggle();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Ease\TWB5\Widgets\Toggle::setProperties
     * @todo   Implement testsetProperties().
     */
    public function testsetProperties() {
        $this->assertEquals('', $this->object->setProperties());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\TWB5\Widgets\Toggle::finalize
     * @todo   Implement testfinalize().
     */
    public function testfinalize() {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
