src/Ease/TWB5/Widgets/*.php     /usr/share/php/EaseTWB5Widgets
debian/autoload.php             /usr/share/php/EaseTWB5Widgets
debian/composer.json            /usr/share/php/EaseTWB5Widgets
tmp/node_modules/bootstrap5-toggle/css/* /usr/share/javascript/bootstrap5/css/
tmp/node_modules/bootstrap5-toggle/js/*  /usr/share/javascript/bootstrap5/js/
php-vitexsoftware-ease-bootstrap5-widgets.svg	usr/share/icons/hicolor/scalable/apps/
debian/io.github.vitexsoftware.php_vitexsoftware_ease_bootstrap5_widgets.metainfo.xml	usr/share/metainfo/
